### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by dotnetwise** [thinkloop/knockout-js-infinite-scroll#2]
As the list number increases, it starts performing slower and slower and taking up much memory.

It would be nice if it would reuse the same number of fixed elements, the same way as the IOS native list does.

**Comment by thinkloop** [comment]
You're right having a fixed number of elements could be an improvement, but there is an important technique that allows this to scale to many thousands of complex items. Say we were working with a Pinterest style layout, where items with heavy content are floated next to each other forever. When items scroll out of view, we can unload their expensive contents (images, comments, styling, etc.), while keeping the top-level containers to maintain document structure:

``` html
<!-- ko foreach: filteredItems.infinitescroll.displayItems -->
   <article class="main-item">
      <!-- ko if: $index() >= $root.filteredItems.infinitescroll.firstVisibleIndex() -->
         <!-- * * complex expensive content * * -->
      <!-- /ko -->
   </article>
<!-- /ko -->
```

We compare $index to firstVisibleIndex and only show the contents of items that are visible on screen. This way you can scroll through many thousands of items since the majority will be empty and super-light.
