### ISSUE TITLE
Problem when there is more than one column

### ISSUE THREAD

**Issue by danielgtaylor** [thinkloop/knockout-js-infinite-scroll#3]
It seems that whenever there is more than one column the infinite scroll eventually just shows blank items. Scroll down to item 150 here:

http://jsfiddle.net/danielgtaylor/9UrGL/

My guess is that it's an issue with the first visible item calculation, but I'm not 100% sure what it might be.

**Comment by thinkloop** [comment]
Hey Daniel,

That's the main use-case I use it for and have a working example of multi-column infinite-scroll here: http://jsfiddle.net/thinkloop/cJGJ9/

The reason this is happening in your example is because of inline-block and its _magic_ spacing: http://stackoverflow.com/questions/16678929/display-inline-block-what-is-that-space

I put a bg color in your example to show you, notice the space around each red block: http://jsfiddle.net/thinkloop/9UrGL/2/

This space is not being accounted for in the item size calculations (because of the weird nature of inline-block), so eventually this discrepancy adds up until it becomes big enough to hide things off screen.

I used the font-size:0 trick to fix it for you: http://jsfiddle.net/thinkloop/9UrGL/3/

Let me know if that works

**Comment by danielgtaylor** [comment]
This does solve the problem, thanks!
